name: tugas_mp1
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Jika kamu benar-benar butuh Auth â†’ versinya harus kompatibel
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.0.0

  # UI
  carousel_slider: ^5.0.0
  google_fonts: ^6.1.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Google.jpg
    - assets/images/Logo.png
    - assets/images/aki.jpg
    - assets/images/busi.jpg
    - assets/images/filter.jpg
    - assets/images/Kampas.jpeg
    - assets/images/oli.jpeg
    - assets/images/rantei.jpeg
    - assets/images/suzuki.png
    - assets/images/yamaha.png
    - assets/images/lainnya.png
    - assets/images/Honda.jpeg
    - assets/images/logohonda.png
    - assets/images/banner.jpg
    - assets/images/welcome1.png
    - assets/images/welcome2.png
    - assets/images/welcome3.png
    - assets/images/login.jpg
    - assets/images/backgroun.jpg
    - assets/images/wiwok.jpg
    - assets/images/detok.jpg
    - assets/images/testt.jpg
    - assets/images/biru.jpg
    - assets/images/promo.jpg
    - assets/images/promo2.jpg
